# Copyright 2024 NVIDIA CORPORATION & AFFILIATES
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# JG TCL script for evaluating the Design2SVA task results
# (1) elaborate testbench generated by a LM via the Design2SVA benchmark
# (2) run formal proof jobs on each of the LM generated assertions 
#
# Possible outcomes:
# 1. Syntax error in the testbench; this will be caught during elaboration and script will immediately exit
# 2. Proof failure: some of the LM generated assertions will be proven false; script proceeds to formal coverage analysis

# Analyze property files
clear -all
# check_cov -init
analyze -clear
analyze -sva ${SVA_PATH}

# Elaborate design and properties
if {[info exists TOP_NAME]} {
    elaborate -top $TOP_NAME
    set top $TOP_NAME
} else {
    elaborate
    set top [get_inst_top]
}
puts "top: $top"

# get clock signal
if {[info exists CLOCK]} {
    clock ${CLOCK}
} else {
    clock -infer
    set clk_list [clock -list signal -silent]
    if {[llength $clk_list] == 0} {
        clock -none
    }
}

# get reset signal
if {[info exists RESET]} {
    set reset_expr [subst $RESET]
    reset ${reset_expr}
} else {
    set reset_infer [reset -analyze -list signal -silent -synchronous]
    if {[llength ${reset_infer}] > 0} {
        reset ${reset_infer}
    } else {
        reset -none
    }
}

# get_design_info
prove -all -time_limit 1m
puts "proofs: [get_status [get_property_list -include {type {assert} disabled {0}}]]"
report
